import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/user'
import Category from '#models/category'
import Referent from '#models/referent'
import Transaction from '#models/transaction'
import { DateTime } from 'luxon'
import string from '@adonisjs/core/helpers/string'

// ── helpers ──────────────────────────────────────────────────────────────────

function ht(ttc: number, rate: number = 20): number {
  return Math.round((ttc / (1 + rate / 100)) * 100) / 100
}

/** Date relative à aujourd'hui : rd(1, 15) = le 15 du mois il y a 1 mois */
function rd(monthsAgo: number, day: number): DateTime {
  return DateTime.now().minus({ months: monthsAgo }).set({ day })
}

/** Code de facture dynamique : inv('SAL', 1, 1) -> 'SAL-2602-001' (si on est en mars 2026) */
function inv(prefix: string, monthsAgo: number, seq: number): string {
  const d = DateTime.now().minus({ months: monthsAgo })
  return `${prefix}-${d.toFormat('yyMM')}-${String(seq).padStart(3, '0')}`
}

// ── transaction descriptor ────────────────────────────────────────────────────

interface TxDef {
  invoice: string
  date: DateTime
  amountAllTax: number
  amountExcludingTax: number
  currency: string
  type: 'RECIPE' | 'EXPENSE' | 'SALARY'
  comment: string | null
  referent: string
  categories: string[]
}

// ── seeder ────────────────────────────────────────────────────────────────────

export default class DemoSeeder extends BaseSeeder {
  async run() {
    // ── 1. Demo user ────────────────────────────────────────────────────────
    const user = await User.updateOrCreate(
      { email: 'demo@example.com' },
      {
        username: 'demo',
        email: 'demo@example.com',
        password: 'Demo1234!',
        confirmTokenSentAt: DateTime.now(),
        confirmToken: string.random(32),
        confirmedAt: DateTime.now(),
        treasury: 0,
        locale: 'fr',
        theme: 'light',
      }
    )

    // ── 2. Categories ────────────────────────────────────────────────────────
    const categoryNames = [
      'Alimentation',
      'Transport',
      'Logement',
      'Santé',
      'Loisirs & Culture',
      'Matériel informatique',
      'Logiciels & Abonnements',
      'Formation',
      'Téléphone & Internet',
      'Services & Comptabilité',
      'Divers',

      // {
      //   invoice: inv('SNI', 1, 1),
      //   date: rd(1, 10),
      //   amountAllTax: 200,
      //   amountExcludingTax: ht(200),
      //   currency: 'EUR',
      //   type: 'RECIPE',
      //   comment: 'Revue et correction code frontend',
      //   referent: 'Startup Innova',
      //   categories: ['Divers'],
      // },
      // {
      //   invoice: inv('CDR', 1, 1),
      //   date: rd(1, 18),
      //   amountAllTax: 180,
      //   amountExcludingTax: ht(180),
      //   currency: 'EUR',
      //   type: 'RECIPE',
      //   comment: 'Nettoyage logs et espace disque',
      //   referent: 'Cabinet Digital RH',
      //   categories: ['Divers'],
      // },
      // {
      //   invoice: inv('PME', 1, 1),
      //   date: rd(1, 25),
      //   amountAllTax: 160,
      //   amountExcludingTax: ht(160),
      //   currency: 'EUR',
      //   type: 'RECIPE',
      //   comment: 'Audit sécurité applicatif',
      //   referent: 'PME Concept',
      //   categories: ['Divers'],
      // },
    ]

    const cats: Record<string, Category> = {}
    for (const name of categoryNames) {
      cats[name] = await Category.updateOrCreate({ name }, { name, userId: user.id })
    }

    // ── 3. Referents ─────────────────────────────────────────────────────────
    const referentNames = [
      'TechStartup SAS',
      'AgenceWeb Solutions',
      'DigitalBoost Agency',
      'E-Commerce Pro',
      'SARL Immobilier Dupont',
      'Amazon',
      'SNCF',
      'Carrefour',
      'OVH Cloud',
      'Apple',
      'Decathlon',
      'Pharmacie Centrale',
      'OpenAI',
      'Udemy',
      'Coursera',
      'Orange',
      'Expert-Comptable Martin',
      'Airbnb',
      'Startup Innova',
      'Cabinet Digital RH',
      'PME Concept',
      'Nexus Consulting',
    ]

    const refs: Record<string, Referent> = {}
    for (const name of referentNames) {
      refs[name] = await Referent.firstOrCreate(
        { name, userId: user.id },
        { name, userId: user.id }
      )
    }

    // Skip if demo transactions already exist
    const existing = await Transaction.query().where('userId', user.id).count('* as total')
    const count = Number((existing[0] as any).$extras.total)
    if (count > 0) return

    // ── 4. Transactions ──────────────────────────────────────────────────────
    const txDefs: TxDef[] = [
      // ═══ 2025-03 ═══
      {
        invoice: inv('SAL', 12, 1),
        date: rd(12, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire mars 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 12, 1),
        date: rd(12, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer mars 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 12, 1),
        date: rd(12, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile mars',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 12, 1),
        date: rd(12, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web mars',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 12, 1),
        date: rd(12, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé mars',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 12, 1),
        date: rd(12, 8),
        amountAllTax: 87.4,
        amountExcludingTax: ht(87.4, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 12, 2),
        date: rd(12, 20),
        amountAllTax: 112.6,
        amountExcludingTax: ht(112.6, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('AGB', 12, 1),
        date: rd(12, 14),
        amountAllTax: 1800,
        amountExcludingTax: ht(1800),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Prestation développement web - Mars',
        referent: 'AgenceWeb Solutions',
        categories: ['Divers'],
      },

      {
        invoice: inv('SNI', 12, 1),
        date: rd(12, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Correction bug interface mobile',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 12, 2),
        date: rd(12, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Intégration API tierce partie',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 12, 3),
        date: rd(12, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation temps de chargement',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 12, 1),
        date: rd(12, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Maintenance préventive système',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 12, 2),
        date: rd(12, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Sauvegarde et vérification BDD',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 12, 3),
        date: rd(12, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Configuration alertes monitoring',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 12, 1),
        date: rd(12, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit technique architecture',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 12, 2),
        date: rd(12, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Analyse performance applicative',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 12, 3),
        date: rd(12, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Évaluation prestataires techniques',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 12, 1),
        date: rd(12, 10),
        amountAllTax: 220,
        amountExcludingTax: ht(220),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mission consulting transformation digitale',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 12, 2),
        date: rd(12, 24),
        amountAllTax: 230,
        amountExcludingTax: ht(230),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Accompagnement recrutement tech',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-04 ═══
      {
        invoice: inv('SAL', 11, 1),
        date: rd(11, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire avril 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 11, 1),
        date: rd(11, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer avril 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 11, 1),
        date: rd(11, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile avril',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 11, 1),
        date: rd(11, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web avril',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 11, 1),
        date: rd(11, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé avril',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 11, 1),
        date: rd(11, 5),
        amountAllTax: 96.2,
        amountExcludingTax: ht(96.2, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 11, 2),
        date: rd(11, 18),
        amountAllTax: 73.5,
        amountExcludingTax: ht(73.5, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('SNC', 11, 1),
        date: rd(11, 9),
        amountAllTax: 82,
        amountExcludingTax: ht(82, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Paris-Lyon (conférence)',
        referent: 'SNCF',
        categories: ['Transport'],
      },
      {
        invoice: inv('AMZ', 11, 1),
        date: rd(11, 22),
        amountAllTax: 149.9,
        amountExcludingTax: ht(149.9),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Clavier mécanique Keychron K2',
        referent: 'Amazon',
        categories: ['Matériel informatique'],
      },
      {
        invoice: inv('DBG', 11, 1),
        date: rd(11, 25),
        amountAllTax: 2400,
        amountExcludingTax: ht(2400),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit SEO & refonte landing page',
        referent: 'DigitalBoost Agency',
        categories: ['Divers'],
      },

      {
        invoice: inv('SNI', 11, 1),
        date: rd(11, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation requêtes SQL',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 11, 2),
        date: rd(11, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Fix régression tests unitaires',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 11, 3),
        date: rd(11, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Implémentation authentification OAuth',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 11, 1),
        date: rd(11, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mise à jour dépendances npm',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 11, 2),
        date: rd(11, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation requêtes lentes',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 11, 3),
        date: rd(11, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue infrastructure cloud',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 11, 1),
        date: rd(11, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil stratégie digitale',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 11, 2),
        date: rd(11, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Atelier découverte DevOps',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 11, 3),
        date: rd(11, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Consultation choix BDD',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 11, 1),
        date: rd(11, 10),
        amountAllTax: 220,
        amountExcludingTax: ht(220),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Accompagnement projet SI',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 11, 2),
        date: rd(11, 24),
        amountAllTax: 230,
        amountExcludingTax: ht(230),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil organisation Agile',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-05 ═══
      {
        invoice: inv('SAL', 10, 1),
        date: rd(10, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire mai 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 10, 1),
        date: rd(10, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer mai 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 10, 1),
        date: rd(10, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile mai',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 10, 1),
        date: rd(10, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web mai',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 10, 1),
        date: rd(10, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé mai',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 10, 1),
        date: rd(10, 10),
        amountAllTax: 108.3,
        amountExcludingTax: ht(108.3, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 10, 2),
        date: rd(10, 25),
        amountAllTax: 65.8,
        amountExcludingTax: ht(65.8, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('UDM', 10, 1),
        date: rd(10, 12),
        amountAllTax: 34.99,
        amountExcludingTax: ht(34.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Formation Docker & Kubernetes',
        referent: 'Udemy',
        categories: ['Formation'],
      },
      {
        invoice: inv('AGB', 10, 1),
        date: rd(10, 20),
        amountAllTax: 3200,
        amountExcludingTax: ht(3200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Développement application mobile - Phase 1',
        referent: 'AgenceWeb Solutions',
        categories: ['Divers'],
      },
      {
        invoice: inv('OAI', 10, 1),
        date: rd(10, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - mai',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },

      {
        invoice: inv('SNI', 10, 1),
        date: rd(10, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Ajout fonctionnalité tableau de bord',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 10, 2),
        date: rd(10, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mise en page responsive mobile',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 10, 3),
        date: rd(10, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Migration TypeScript strict',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 10, 1),
        date: rd(10, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Monitoring et rapport mensuel',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 10, 2),
        date: rd(10, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Déploiement hotfix production',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 10, 3),
        date: rd(10, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Rotation certificats SSL',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 10, 1),
        date: rd(10, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue de code et recommandations',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 10, 2),
        date: rd(10, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Rédaction cahier des charges',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 10, 3),
        date: rd(10, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil migration cloud',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 10, 1),
        date: rd(10, 10),
        amountAllTax: 220,
        amountExcludingTax: ht(220),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil architecture microservices',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 10, 2),
        date: rd(10, 24),
        amountAllTax: 230,
        amountExcludingTax: ht(230),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mission expert technique',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-06 ═══
      {
        invoice: inv('SAL', 9, 1),
        date: rd(9, 27),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire juin 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 9, 1),
        date: rd(9, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer juin 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 9, 1),
        date: rd(9, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile juin',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 9, 1),
        date: rd(9, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web juin',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 9, 1),
        date: rd(9, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé juin',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 9, 1),
        date: rd(9, 7),
        amountAllTax: 91.7,
        amountExcludingTax: ht(91.7, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 9, 2),
        date: rd(9, 21),
        amountAllTax: 78.9,
        amountExcludingTax: ht(78.9, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('SNC', 9, 1),
        date: rd(9, 3),
        amountAllTax: 54,
        amountExcludingTax: ht(54, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Lyon-Marseille (réunion client)',
        referent: 'SNCF',
        categories: ['Transport'],
      },
      {
        invoice: inv('APL', 9, 1),
        date: rd(9, 18),
        amountAllTax: 1199,
        amountExcludingTax: ht(1199),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'MacBook Air M3',
        referent: 'Apple',
        categories: ['Matériel informatique'],
      },
      {
        invoice: inv('ECP', 9, 1),
        date: rd(9, 30),
        amountAllTax: 1800,
        amountExcludingTax: ht(1800),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Intégration e-commerce - Boutique mode',
        referent: 'E-Commerce Pro',
        categories: ['Divers'],
      },
      {
        invoice: inv('OAI', 9, 1),
        date: rd(9, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - juin',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },

      {
        invoice: inv('SNI', 9, 1),
        date: rd(9, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Refactoring composants React',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 9, 2),
        date: rd(9, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Développement formulaire multi-étapes',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 9, 3),
        date: rd(9, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue et correction code frontend',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 9, 1),
        date: rd(9, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Patch sécurité critique',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 9, 2),
        date: rd(9, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit journaux système',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 9, 3),
        date: rd(9, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Nettoyage logs et espace disque',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 9, 1),
        date: rd(9, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Accompagnement choix technologique',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 9, 2),
        date: rd(9, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Formation équipe développeurs',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 9, 3),
        date: rd(9, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit sécurité applicatif',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 9, 1),
        date: rd(9, 10),
        amountAllTax: 220,
        amountExcludingTax: ht(220),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Étude faisabilité technique',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 9, 2),
        date: rd(9, 24),
        amountAllTax: 230,
        amountExcludingTax: ht(230),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Analyse ROI digital',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-07 ═══
      {
        invoice: inv('SAL', 8, 1),
        date: rd(8, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire juillet 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 8, 1),
        date: rd(8, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer juillet 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 8, 1),
        date: rd(8, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile juillet',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 8, 1),
        date: rd(8, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web juillet',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 8, 1),
        date: rd(8, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé juillet',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 8, 1),
        date: rd(8, 6),
        amountAllTax: 103.2,
        amountExcludingTax: ht(103.2, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 8, 2),
        date: rd(8, 19),
        amountAllTax: 88.4,
        amountExcludingTax: ht(88.4, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('DEC', 8, 1),
        date: rd(8, 14),
        amountAllTax: 89.99,
        amountExcludingTax: ht(89.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Vélo électrique (pièces)',
        referent: 'Decathlon',
        categories: ['Transport', 'Loisirs & Culture'],
      },
      {
        invoice: inv('VAC', 8, 1),
        date: rd(8, 5),
        amountAllTax: 1350,
        amountExcludingTax: 1350,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Location gîte vacances été - 10 nuits Bretagne',
        referent: 'Airbnb',
        categories: ['Loisirs & Culture'],
      },
      {
        invoice: inv('TRP', 8, 1),
        date: rd(8, 3),
        amountAllTax: 428,
        amountExcludingTax: ht(428, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Billets train Paris-Bretagne aller-retour',
        referent: 'SNCF',
        categories: ['Transport'],
      },
      {
        invoice: inv('DEC', 8, 2),
        date: rd(8, 9),
        amountAllTax: 245,
        amountExcludingTax: ht(245),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Matériel camping et randonnée',
        referent: 'Decathlon',
        categories: ['Loisirs & Culture'],
      },
      {
        invoice: inv('OAI', 8, 1),
        date: rd(8, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - juillet',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },

      {
        invoice: inv('SNI', 8, 1),
        date: rd(8, 10),
        amountAllTax: 90,
        amountExcludingTax: ht(90),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Intégration API tierce partie',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 8, 1),
        date: rd(8, 18),
        amountAllTax: 80,
        amountExcludingTax: ht(80),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Sauvegarde et vérification BDD',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 8, 1),
        date: rd(8, 25),
        amountAllTax: 4550,
        amountExcludingTax: ht(4550),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Analyse performance applicative',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      // ═══ 2025-08 ═══
      {
        invoice: inv('SAL', 7, 1),
        date: rd(7, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire août 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 7, 1),
        date: rd(7, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer août 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 7, 1),
        date: rd(7, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile août',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 7, 1),
        date: rd(7, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web août',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 7, 1),
        date: rd(7, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé août',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 7, 1),
        date: rd(7, 9),
        amountAllTax: 118.6,
        amountExcludingTax: ht(118.6, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 7, 2),
        date: rd(7, 26),
        amountAllTax: 79.3,
        amountExcludingTax: ht(79.3, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('SNC', 7, 1),
        date: rd(7, 5),
        amountAllTax: 128,
        amountExcludingTax: ht(128, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Paris-Nice (vacances)',
        referent: 'SNCF',
        categories: ['Transport', 'Loisirs & Culture'],
      },
      {
        invoice: inv('AMZ', 7, 1),
        date: rd(7, 20),
        amountAllTax: 329.99,
        amountExcludingTax: ht(329.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Écran Dell 27" 4K',
        referent: 'Amazon',
        categories: ['Matériel informatique'],
      },
      {
        invoice: inv('OAI', 7, 1),
        date: rd(7, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - août',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('AGB', 7, 1),
        date: rd(7, 29),
        amountAllTax: 2800,
        amountExcludingTax: ht(2800),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Développement application mobile - Phase 2',
        referent: 'AgenceWeb Solutions',
        categories: ['Divers'],
      },

      {
        invoice: inv('SNI', 7, 1),
        date: rd(7, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Fix régression tests unitaires',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 7, 2),
        date: rd(7, 14),
        amountAllTax: 860,
        amountExcludingTax: ht(860),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Implémentation authentification OAuth',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 7, 3),
        date: rd(7, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation requêtes SQL',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 7, 1),
        date: rd(7, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation requêtes lentes',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 7, 2),
        date: rd(7, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue infrastructure cloud',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 7, 3),
        date: rd(7, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mise à jour dépendances npm',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 7, 1),
        date: rd(7, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Atelier découverte DevOps',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 7, 2),
        date: rd(7, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Consultation choix BDD',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 7, 3),
        date: rd(7, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil stratégie digitale',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 7, 1),
        date: rd(7, 10),
        amountAllTax: 1500,
        amountExcludingTax: ht(1500),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit maturité numérique',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 7, 2),
        date: rd(7, 24),
        amountAllTax: 1200,
        amountExcludingTax: ht(1200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Expertise cloud strategy',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-09 ═══
      {
        invoice: inv('SAL', 6, 1),
        date: rd(6, 26),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire septembre 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 6, 1),
        date: rd(6, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer septembre 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 6, 1),
        date: rd(6, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile septembre',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 6, 1),
        date: rd(6, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web septembre',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 6, 1),
        date: rd(6, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé septembre',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 6, 1),
        date: rd(6, 4),
        amountAllTax: 94.5,
        amountExcludingTax: ht(94.5, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 6, 2),
        date: rd(6, 17),
        amountAllTax: 86.2,
        amountExcludingTax: ht(86.2, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 6, 3),
        date: rd(6, 29),
        amountAllTax: 61.4,
        amountExcludingTax: ht(61.4, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CRS', 6, 1),
        date: rd(6, 8),
        amountAllTax: 89,
        amountExcludingTax: ht(89),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Formation React Advanced',
        referent: 'Coursera',
        categories: ['Formation'],
      },
      {
        invoice: inv('ECM', 6, 1),
        date: rd(6, 24),
        amountAllTax: 3500,
        amountExcludingTax: ht(3500),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Refonte boutique e-commerce complète',
        referent: 'E-Commerce Pro',
        categories: ['Divers'],
      },
      {
        invoice: inv('OAI', 6, 1),
        date: rd(6, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - septembre',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('XCM', 6, 1),
        date: rd(6, 20),
        amountAllTax: 350,
        amountExcludingTax: ht(350),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Honoraires comptables T3 2025',
        referent: 'Expert-Comptable Martin',
        categories: ['Services & Comptabilité'],
      },

      {
        invoice: inv('SNI', 6, 1),
        date: rd(6, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mise en page responsive mobile',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 6, 2),
        date: rd(6, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Migration TypeScript strict',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 6, 3),
        date: rd(6, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Ajout fonctionnalité tableau de bord',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 6, 1),
        date: rd(6, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Déploiement hotfix production',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 6, 2),
        date: rd(6, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Rotation certificats SSL',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 6, 3),
        date: rd(6, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Monitoring et rapport mensuel',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 6, 1),
        date: rd(6, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Rédaction cahier des charges',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 6, 2),
        date: rd(6, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil migration cloud',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 6, 3),
        date: rd(6, 23),
        amountAllTax: 3560,
        amountExcludingTax: ht(3560),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue de code et recommandations',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 6, 1),
        date: rd(6, 10),
        amountAllTax: 1200,
        amountExcludingTax: ht(1200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Accompagnement recrutement tech',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 6, 2),
        date: rd(6, 24),
        amountAllTax: 1500,
        amountExcludingTax: ht(1500),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mission consulting transformation digitale',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-10 ═══
      {
        invoice: inv('SAL', 5, 1),
        date: rd(5, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire octobre 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 5, 1),
        date: rd(5, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer octobre 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 5, 1),
        date: rd(5, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile octobre',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 5, 1),
        date: rd(5, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web octobre',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 5, 1),
        date: rd(5, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé octobre',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 5, 1),
        date: rd(5, 11),
        amountAllTax: 99.8,
        amountExcludingTax: ht(99.8, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 5, 2),
        date: rd(5, 24),
        amountAllTax: 74.6,
        amountExcludingTax: ht(74.6, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('AMZ', 5, 1),
        date: rd(5, 7),
        amountAllTax: 49.9,
        amountExcludingTax: ht(49.9),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hub USB-C 7 en 1',
        referent: 'Amazon',
        categories: ['Matériel informatique'],
      },
      {
        invoice: inv('SNC', 5, 1),
        date: rd(5, 15),
        amountAllTax: 67,
        amountExcludingTax: ht(67, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Lyon-Paris (rendez-vous professionnel)',
        referent: 'SNCF',
        categories: ['Transport'],
      },
      {
        invoice: inv('MAC', 5, 1),
        date: rd(5, 7),
        amountAllTax: 2399,
        amountExcludingTax: ht(2399),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'MacBook Pro 14" M4 - renouvellement poste de travail',
        referent: 'Apple',
        categories: ['Matériel informatique'],
      },
      {
        invoice: inv('OAI', 5, 1),
        date: rd(5, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - octobre',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('PHR', 5, 1),
        date: rd(5, 18),
        amountAllTax: 38.5,
        amountExcludingTax: ht(38.5, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Médicaments et compléments',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },

      {
        invoice: inv('SNI', 5, 1),
        date: rd(5, 10),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Développement formulaire multi-étapes',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 5, 1),
        date: rd(5, 18),
        amountAllTax: 180,
        amountExcludingTax: ht(180),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit journaux système',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 5, 1),
        date: rd(5, 25),
        amountAllTax: 2500,
        amountExcludingTax: ht(2500),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Formation équipe développeurs',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      // ═══ 2025-11 ═══
      {
        invoice: inv('SAL', 4, 1),
        date: rd(4, 27),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire novembre 2025',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 4, 1),
        date: rd(4, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer novembre 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 4, 1),
        date: rd(4, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile novembre',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 4, 1),
        date: rd(4, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web novembre',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 4, 1),
        date: rd(4, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé novembre',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 4, 1),
        date: rd(4, 8),
        amountAllTax: 107.4,
        amountExcludingTax: ht(107.4, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 4, 2),
        date: rd(4, 22),
        amountAllTax: 92.8,
        amountExcludingTax: ht(92.8, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('AMZ', 4, 1),
        date: rd(4, 29),
        amountAllTax: 199.99,
        amountExcludingTax: ht(199.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'SSD externe 2To Samsung (Black Friday)',
        referent: 'Amazon',
        categories: ['Matériel informatique'],
      },
      {
        invoice: inv('DBG', 4, 1),
        date: rd(4, 20),
        amountAllTax: 2200,
        amountExcludingTax: ht(2200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Campagne publicitaire Google Ads - setup',
        referent: 'DigitalBoost Agency',
        categories: ['Divers'],
      },
      {
        invoice: inv('OAI', 4, 1),
        date: rd(4, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - novembre',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('DEC', 4, 1),
        date: rd(4, 12),
        amountAllTax: 129.99,
        amountExcludingTax: ht(129.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Trottinette électrique',
        referent: 'Decathlon',
        categories: ['Transport', 'Loisirs & Culture'],
      },

      {
        invoice: inv('SNI', 4, 1),
        date: rd(4, 7),
        amountAllTax: 550,
        amountExcludingTax: ht(550),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation temps de chargement',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 4, 2),
        date: rd(4, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Correction bug interface mobile',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 4, 3),
        date: rd(4, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Intégration API tierce partie',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 4, 1),
        date: rd(4, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Configuration alertes monitoring',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 4, 2),
        date: rd(4, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Maintenance préventive système',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 4, 3),
        date: rd(4, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Sauvegarde et vérification BDD',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 4, 1),
        date: rd(4, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Évaluation prestataires techniques',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 4, 2),
        date: rd(4, 12),
        amountAllTax: 4000,
        amountExcludingTax: ht(4000),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Audit technique architecture',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 4, 3),
        date: rd(4, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Analyse performance applicative',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 4, 1),
        date: rd(4, 10),
        amountAllTax: 1800,
        amountExcludingTax: ht(1800),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mission expert technique',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 4, 2),
        date: rd(4, 24),
        amountAllTax: 2450,
        amountExcludingTax: ht(2450),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil architecture microservices',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2025-12 ═══
      {
        invoice: inv('SAL', 3, 1),
        date: rd(3, 24),
        amountAllTax: 3200,
        amountExcludingTax: 3200,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire décembre 2025 (prime incluse)',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 3, 1),
        date: rd(3, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer décembre 2025',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 3, 1),
        date: rd(3, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile décembre',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 3, 1),
        date: rd(3, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web décembre',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 3, 1),
        date: rd(3, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé décembre',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 3, 1),
        date: rd(3, 6),
        amountAllTax: 142.3,
        amountExcludingTax: ht(142.3, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires (fêtes)',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 3, 2),
        date: rd(3, 20),
        amountAllTax: 189.5,
        amountExcludingTax: ht(189.5, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Repas de fêtes',
        referent: 'Carrefour',
        categories: ['Alimentation', 'Loisirs & Culture'],
      },
      {
        invoice: inv('APL', 3, 1),
        date: rd(3, 10),
        amountAllTax: 129,
        amountExcludingTax: ht(129),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'AirPods Pro 2',
        referent: 'Apple',
        categories: ['Loisirs & Culture', 'Matériel informatique'],
      },
      {
        invoice: inv('SNC', 3, 1),
        date: rd(3, 23),
        amountAllTax: 95,
        amountExcludingTax: ht(95, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Train famille (Noël)',
        referent: 'SNCF',
        categories: ['Transport', 'Loisirs & Culture'],
      },
      {
        invoice: inv('ECP', 3, 1),
        date: rd(3, 19),
        amountAllTax: 4000,
        amountExcludingTax: ht(4000),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Développement tunnel de vente complet',
        referent: 'E-Commerce Pro',
        categories: ['Divers'],
      },
      {
        invoice: inv('OAI', 3, 1),
        date: rd(3, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - décembre',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('XCM', 3, 1),
        date: rd(3, 15),
        amountAllTax: 350,
        amountExcludingTax: ht(350),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Honoraires comptables T4 2025',
        referent: 'Expert-Comptable Martin',
        categories: ['Services & Comptabilité'],
      },

      {
        invoice: inv('SNI', 3, 1),
        date: rd(3, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Implémentation authentification OAuth',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 3, 2),
        date: rd(3, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation requêtes SQL',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 3, 3),
        date: rd(3, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Fix régression tests unitaires',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 3, 1),
        date: rd(3, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue infrastructure cloud',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 3, 2),
        date: rd(3, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mise à jour dépendances npm',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 3, 3),
        date: rd(3, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Optimisation requêtes lentes',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 3, 1),
        date: rd(3, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Consultation choix BDD',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 3, 2),
        date: rd(3, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil stratégie digitale',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 3, 3),
        date: rd(3, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Atelier découverte DevOps',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 3, 1),
        date: rd(3, 10),
        amountAllTax: 220,
        amountExcludingTax: ht(220),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Analyse ROI digital',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 3, 2),
        date: rd(3, 24),
        amountAllTax: 230,
        amountExcludingTax: ht(230),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Étude faisabilité technique',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2026-01 ═══
      {
        invoice: inv('SAL', 2, 1),
        date: rd(2, 28),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire janvier 2026',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 2, 1),
        date: rd(2, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer janvier 2026',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 2, 1),
        date: rd(2, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile janvier',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 2, 1),
        date: rd(2, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web janvier',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 2, 1),
        date: rd(2, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé janvier',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 2, 1),
        date: rd(2, 9),
        amountAllTax: 89.7,
        amountExcludingTax: ht(89.7, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 2, 2),
        date: rd(2, 23),
        amountAllTax: 76.4,
        amountExcludingTax: ht(76.4, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('UDM', 2, 1),
        date: rd(2, 7),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Formation TypeScript avancé',
        referent: 'Udemy',
        categories: ['Formation'],
      },
      {
        invoice: inv('AGB', 2, 1),
        date: rd(2, 28),
        amountAllTax: 2600,
        amountExcludingTax: ht(2600),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Projet site vitrine + CMS - janvier',
        referent: 'AgenceWeb Solutions',
        categories: ['Divers'],
      },
      {
        invoice: inv('OAI', 2, 1),
        date: rd(2, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - janvier',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('AMZ', 2, 1),
        date: rd(2, 18),
        amountAllTax: 74.99,
        amountExcludingTax: ht(74.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Câbles et adaptateurs divers',
        referent: 'Amazon',
        categories: ['Matériel informatique'],
      },

      {
        invoice: inv('SNI', 2, 1),
        date: rd(2, 7),
        amountAllTax: 120,
        amountExcludingTax: ht(120),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Migration TypeScript strict',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 2, 2),
        date: rd(2, 14),
        amountAllTax: 145,
        amountExcludingTax: ht(145),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Ajout fonctionnalité tableau de bord',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('SNI', 2, 3),
        date: rd(2, 21),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Mise en page responsive mobile',
        referent: 'Startup Innova',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 2, 1),
        date: rd(2, 5),
        amountAllTax: 190,
        amountExcludingTax: ht(190),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Rotation certificats SSL',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 2, 2),
        date: rd(2, 19),
        amountAllTax: 175,
        amountExcludingTax: ht(175),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Monitoring et rapport mensuel',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('CDR', 2, 3),
        date: rd(2, 26),
        amountAllTax: 200,
        amountExcludingTax: ht(200),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Déploiement hotfix production',
        referent: 'Cabinet Digital RH',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 2, 1),
        date: rd(2, 3),
        amountAllTax: 110,
        amountExcludingTax: ht(110),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil migration cloud',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 2, 2),
        date: rd(2, 12),
        amountAllTax: 130,
        amountExcludingTax: ht(130),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Revue de code et recommandations',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('PME', 2, 3),
        date: rd(2, 23),
        amountAllTax: 115,
        amountExcludingTax: ht(115),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Rédaction cahier des charges',
        referent: 'PME Concept',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 2, 1),
        date: rd(2, 10),
        amountAllTax: 220,
        amountExcludingTax: ht(220),
        currency: 'EUR',
        type: 'RECIPE',
        comment: 'Conseil modernisation SI',
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      {
        invoice: inv('NXC', 2, 2),
        date: rd(2, 24),
        amountAllTax: 230,
        amountExcludingTax: ht(230),
        currency: 'EUR',
        type: 'RECIPE',
        comment: "Expertise technique appel d'offre",
        referent: 'Nexus Consulting',
        categories: ['Divers'],
      },
      // ═══ 2026-02 ═══
      {
        invoice: inv('SAL', 1, 1),
        date: rd(1, 27),
        amountAllTax: 2850,
        amountExcludingTax: 2850,
        currency: 'EUR',
        type: 'SALARY',
        comment: 'Salaire février 2026',
        referent: 'TechStartup SAS',
        categories: ['Divers'],
      },
      {
        invoice: inv('LOY', 1, 1),
        date: rd(1, 1),
        amountAllTax: 950,
        amountExcludingTax: 950,
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Loyer février 2026',
        referent: 'SARL Immobilier Dupont',
        categories: ['Logement'],
      },
      {
        invoice: inv('TEL', 1, 1),
        date: rd(1, 5),
        amountAllTax: 29.99,
        amountExcludingTax: ht(29.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Forfait mobile février',
        referent: 'Orange',
        categories: ['Téléphone & Internet'],
      },
      {
        invoice: inv('OVH', 1, 1),
        date: rd(1, 10),
        amountAllTax: 19.99,
        amountExcludingTax: ht(19.99),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Hébergement web février',
        referent: 'OVH Cloud',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('MUT', 1, 1),
        date: rd(1, 15),
        amountAllTax: 54,
        amountExcludingTax: ht(54),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Mutuelle santé février',
        referent: 'Pharmacie Centrale',
        categories: ['Santé'],
      },
      {
        invoice: inv('CAR', 1, 1),
        date: rd(1, 6),
        amountAllTax: 93.2,
        amountExcludingTax: ht(93.2, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CAR', 1, 2),
        date: rd(1, 20),
        amountAllTax: 81.6,
        amountExcludingTax: ht(81.6, 5.5),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Courses alimentaires',
        referent: 'Carrefour',
        categories: ['Alimentation'],
      },
      {
        invoice: inv('CPT', 1, 1),
        date: rd(1, 14),
        amountAllTax: 1800,
        amountExcludingTax: ht(1800),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Bilan comptable annuel 2025',
        referent: 'Expert-Comptable Martin',
        categories: ['Services & Comptabilité'],
      },
      {
        invoice: inv('OAI', 1, 1),
        date: rd(1, 1),
        amountAllTax: 24,
        amountExcludingTax: ht(24),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'ChatGPT Plus - février',
        referent: 'OpenAI',
        categories: ['Logiciels & Abonnements'],
      },
      {
        invoice: inv('SNC', 1, 1),
        date: rd(1, 10),
        amountAllTax: 72,
        amountExcludingTax: ht(72, 10),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Déplacement professionnel Paris',
        referent: 'SNCF',
        categories: ['Transport'],
      },
      {
        invoice: inv('XCM', 1, 1),
        date: rd(1, 28),
        amountAllTax: 350,
        amountExcludingTax: ht(350),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Honoraires comptables Q1 2026',
        referent: 'Expert-Comptable Martin',
        categories: ['Services & Comptabilité'],
      },
      {
        invoice: inv('CRS', 1, 1),
        date: rd(1, 18),
        amountAllTax: 149,
        amountExcludingTax: ht(149),
        currency: 'EUR',
        type: 'EXPENSE',
        comment: 'Certification AWS Solutions Architect',
        referent: 'Coursera',
        categories: ['Formation'],
      },
    ]

    // ── 5. Create transactions ────────────────────────────────────────────────
    for (const def of txDefs) {
      const transaction = await Transaction.create({
        userId: user.id,
        invoice: def.invoice,
        date: def.date,
        amountAllTax: def.amountAllTax,
        amountExcludingTax: def.amountExcludingTax,
        currency: def.currency,
        type: def.type as any,
        comment: def.comment,
        referentId: refs[def.referent].id,
      })

      const categoryInstances = def.categories
        .map((name) => cats[name])
        .filter(Boolean)
        .map((c) => c.id)

      await transaction.related('categories').attach(categoryInstances)
    }
  }
}
